version: '3'
services:
  db:
    container_name: db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=Vale2016
      - MYSQL_DATABASE=prueba
      - MYSQL_USER=prueba
      - MYSQL_PASSWORD=Vale2016
    volumes:
      - ./db/script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - "3306:3306"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=Vale2016
    ports:
      - "3000:3000"
    depends_on:
      - db
  product:
    build:
      context: ./app-Producto
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=Vale2016
    ports:
      - "3002:3002"
    depends_on:
      - db
  frontend:
    build:
      context: ./client/clientreac
      dockerfile: Dockerfile
    ports:
      - '8000:3000'
    volumes:
      - './:/app'
    environment:
      - NODE_ENV=production
    command: npm start
    
    
     
